interface CountryInfo { flag: string; name: string; prefix: string }

// Sorted longest-prefix-first so +355 matches before +35, etc.
const CODES: Array<{ prefix: string; iso: string; name: string }> = [
  { prefix: "+1242", iso: "BS", name: "Bahamas" },
  { prefix: "+1246", iso: "BB", name: "Barbados" },
  { prefix: "+1264", iso: "AI", name: "Anguilla" },
  { prefix: "+1268", iso: "AG", name: "Antigua & Barbuda" },
  { prefix: "+1284", iso: "VG", name: "British Virgin Islands" },
  { prefix: "+1340", iso: "VI", name: "US Virgin Islands" },
  { prefix: "+1345", iso: "KY", name: "Cayman Islands" },
  { prefix: "+1441", iso: "BM", name: "Bermuda" },
  { prefix: "+1473", iso: "GD", name: "Grenada" },
  { prefix: "+1649", iso: "TC", name: "Turks & Caicos" },
  { prefix: "+1664", iso: "MS", name: "Montserrat" },
  { prefix: "+1671", iso: "GU", name: "Guam" },
  { prefix: "+1684", iso: "AS", name: "American Samoa" },
  { prefix: "+1758", iso: "LC", name: "Saint Lucia" },
  { prefix: "+1767", iso: "DM", name: "Dominica" },
  { prefix: "+1784", iso: "VC", name: "Saint Vincent" },
  { prefix: "+1787", iso: "PR", name: "Puerto Rico" },
  { prefix: "+1809", iso: "DO", name: "Dominican Republic" },
  { prefix: "+1868", iso: "TT", name: "Trinidad & Tobago" },
  { prefix: "+1869", iso: "KN", name: "Saint Kitts & Nevis" },
  { prefix: "+1876", iso: "JM", name: "Jamaica" },
  { prefix: "+1939", iso: "PR", name: "Puerto Rico" },
  { prefix: "+7840", iso: "GE", name: "Abkhazia" },
  { prefix: "+7940", iso: "GE", name: "Abkhazia" },
  { prefix: "+355",  iso: "AL", name: "Albania" },
  { prefix: "+356",  iso: "MT", name: "Malta" },
  { prefix: "+357",  iso: "CY", name: "Cyprus" },
  { prefix: "+358",  iso: "FI", name: "Finland" },
  { prefix: "+359",  iso: "BG", name: "Bulgaria" },
  { prefix: "+370",  iso: "LT", name: "Lithuania" },
  { prefix: "+371",  iso: "LV", name: "Latvia" },
  { prefix: "+372",  iso: "EE", name: "Estonia" },
  { prefix: "+373",  iso: "MD", name: "Moldova" },
  { prefix: "+374",  iso: "AM", name: "Armenia" },
  { prefix: "+375",  iso: "BY", name: "Belarus" },
  { prefix: "+376",  iso: "AD", name: "Andorra" },
  { prefix: "+377",  iso: "MC", name: "Monaco" },
  { prefix: "+378",  iso: "SM", name: "San Marino" },
  { prefix: "+380",  iso: "UA", name: "Ukraine" },
  { prefix: "+381",  iso: "RS", name: "Serbia" },
  { prefix: "+382",  iso: "ME", name: "Montenegro" },
  { prefix: "+383",  iso: "XK", name: "Kosovo" },
  { prefix: "+385",  iso: "HR", name: "Croatia" },
  { prefix: "+386",  iso: "SI", name: "Slovenia" },
  { prefix: "+387",  iso: "BA", name: "Bosnia & Herzegovina" },
  { prefix: "+389",  iso: "MK", name: "North Macedonia" },
  { prefix: "+420",  iso: "CZ", name: "Czech Republic" },
  { prefix: "+421",  iso: "SK", name: "Slovakia" },
  { prefix: "+423",  iso: "LI", name: "Liechtenstein" },
  { prefix: "+501",  iso: "BZ", name: "Belize" },
  { prefix: "+502",  iso: "GT", name: "Guatemala" },
  { prefix: "+503",  iso: "SV", name: "El Salvador" },
  { prefix: "+504",  iso: "HN", name: "Honduras" },
  { prefix: "+505",  iso: "NI", name: "Nicaragua" },
  { prefix: "+506",  iso: "CR", name: "Costa Rica" },
  { prefix: "+507",  iso: "PA", name: "Panama" },
  { prefix: "+509",  iso: "HT", name: "Haiti" },
  { prefix: "+590",  iso: "GP", name: "Guadeloupe" },
  { prefix: "+591",  iso: "BO", name: "Bolivia" },
  { prefix: "+592",  iso: "GY", name: "Guyana" },
  { prefix: "+593",  iso: "EC", name: "Ecuador" },
  { prefix: "+595",  iso: "PY", name: "Paraguay" },
  { prefix: "+597",  iso: "SR", name: "Suriname" },
  { prefix: "+598",  iso: "UY", name: "Uruguay" },
  { prefix: "+599",  iso: "CW", name: "Curaçao" },
  { prefix: "+670",  iso: "TL", name: "Timor-Leste" },
  { prefix: "+672",  iso: "NF", name: "Norfolk Island" },
  { prefix: "+673",  iso: "BN", name: "Brunei" },
  { prefix: "+674",  iso: "NR", name: "Nauru" },
  { prefix: "+675",  iso: "PG", name: "Papua New Guinea" },
  { prefix: "+676",  iso: "TO", name: "Tonga" },
  { prefix: "+677",  iso: "SB", name: "Solomon Islands" },
  { prefix: "+678",  iso: "VU", name: "Vanuatu" },
  { prefix: "+679",  iso: "FJ", name: "Fiji" },
  { prefix: "+680",  iso: "PW", name: "Palau" },
  { prefix: "+682",  iso: "CK", name: "Cook Islands" },
  { prefix: "+685",  iso: "WS", name: "Samoa" },
  { prefix: "+686",  iso: "KI", name: "Kiribati" },
  { prefix: "+687",  iso: "NC", name: "New Caledonia" },
  { prefix: "+688",  iso: "TV", name: "Tuvalu" },
  { prefix: "+689",  iso: "PF", name: "French Polynesia" },
  { prefix: "+690",  iso: "TK", name: "Tokelau" },
  { prefix: "+691",  iso: "FM", name: "Micronesia" },
  { prefix: "+692",  iso: "MH", name: "Marshall Islands" },
  { prefix: "+850",  iso: "KP", name: "North Korea" },
  { prefix: "+852",  iso: "HK", name: "Hong Kong" },
  { prefix: "+853",  iso: "MO", name: "Macau" },
  { prefix: "+855",  iso: "KH", name: "Cambodia" },
  { prefix: "+856",  iso: "LA", name: "Laos" },
  { prefix: "+880",  iso: "BD", name: "Bangladesh" },
  { prefix: "+886",  iso: "TW", name: "Taiwan" },
  { prefix: "+960",  iso: "MV", name: "Maldives" },
  { prefix: "+961",  iso: "LB", name: "Lebanon" },
  { prefix: "+962",  iso: "JO", name: "Jordan" },
  { prefix: "+963",  iso: "SY", name: "Syria" },
  { prefix: "+964",  iso: "IQ", name: "Iraq" },
  { prefix: "+965",  iso: "KW", name: "Kuwait" },
  { prefix: "+966",  iso: "SA", name: "Saudi Arabia" },
  { prefix: "+967",  iso: "YE", name: "Yemen" },
  { prefix: "+968",  iso: "OM", name: "Oman" },
  { prefix: "+970",  iso: "PS", name: "Palestine" },
  { prefix: "+971",  iso: "AE", name: "United Arab Emirates" },
  { prefix: "+972",  iso: "IL", name: "Israel" },
  { prefix: "+973",  iso: "BH", name: "Bahrain" },
  { prefix: "+974",  iso: "QA", name: "Qatar" },
  { prefix: "+975",  iso: "BT", name: "Bhutan" },
  { prefix: "+976",  iso: "MN", name: "Mongolia" },
  { prefix: "+977",  iso: "NP", name: "Nepal" },
  { prefix: "+992",  iso: "TJ", name: "Tajikistan" },
  { prefix: "+993",  iso: "TM", name: "Turkmenistan" },
  { prefix: "+994",  iso: "AZ", name: "Azerbaijan" },
  { prefix: "+995",  iso: "GE", name: "Georgia" },
  { prefix: "+996",  iso: "KG", name: "Kyrgyzstan" },
  { prefix: "+998",  iso: "UZ", name: "Uzbekistan" },
  // 2-digit prefixes
  { prefix: "+20",   iso: "EG", name: "Egypt" },
  { prefix: "+27",   iso: "ZA", name: "South Africa" },
  { prefix: "+30",   iso: "GR", name: "Greece" },
  { prefix: "+31",   iso: "NL", name: "Netherlands" },
  { prefix: "+32",   iso: "BE", name: "Belgium" },
  { prefix: "+33",   iso: "FR", name: "France" },
  { prefix: "+34",   iso: "ES", name: "Spain" },
  { prefix: "+36",   iso: "HU", name: "Hungary" },
  { prefix: "+39",   iso: "IT", name: "Italy" },
  { prefix: "+40",   iso: "RO", name: "Romania" },
  { prefix: "+41",   iso: "CH", name: "Switzerland" },
  { prefix: "+43",   iso: "AT", name: "Austria" },
  { prefix: "+44",   iso: "GB", name: "United Kingdom" },
  { prefix: "+45",   iso: "DK", name: "Denmark" },
  { prefix: "+46",   iso: "SE", name: "Sweden" },
  { prefix: "+47",   iso: "NO", name: "Norway" },
  { prefix: "+48",   iso: "PL", name: "Poland" },
  { prefix: "+49",   iso: "DE", name: "Germany" },
  { prefix: "+51",   iso: "PE", name: "Peru" },
  { prefix: "+52",   iso: "MX", name: "Mexico" },
  { prefix: "+53",   iso: "CU", name: "Cuba" },
  { prefix: "+54",   iso: "AR", name: "Argentina" },
  { prefix: "+55",   iso: "BR", name: "Brazil" },
  { prefix: "+56",   iso: "CL", name: "Chile" },
  { prefix: "+57",   iso: "CO", name: "Colombia" },
  { prefix: "+58",   iso: "VE", name: "Venezuela" },
  { prefix: "+60",   iso: "MY", name: "Malaysia" },
  { prefix: "+61",   iso: "AU", name: "Australia" },
  { prefix: "+62",   iso: "ID", name: "Indonesia" },
  { prefix: "+63",   iso: "PH", name: "Philippines" },
  { prefix: "+64",   iso: "NZ", name: "New Zealand" },
  { prefix: "+65",   iso: "SG", name: "Singapore" },
  { prefix: "+66",   iso: "TH", name: "Thailand" },
  { prefix: "+81",   iso: "JP", name: "Japan" },
  { prefix: "+82",   iso: "KR", name: "South Korea" },
  { prefix: "+84",   iso: "VN", name: "Vietnam" },
  { prefix: "+86",   iso: "CN", name: "China" },
  { prefix: "+90",   iso: "TR", name: "Turkey" },
  { prefix: "+91",   iso: "IN", name: "India" },
  { prefix: "+92",   iso: "PK", name: "Pakistan" },
  { prefix: "+93",   iso: "AF", name: "Afghanistan" },
  { prefix: "+94",   iso: "LK", name: "Sri Lanka" },
  { prefix: "+95",   iso: "MM", name: "Myanmar" },
  { prefix: "+98",   iso: "IR", name: "Iran" },
  // 1-digit prefixes last
  { prefix: "+1",    iso: "US", name: "United States" },
  { prefix: "+7",    iso: "RU", name: "Russia" },
];

function isoToFlag(iso: string): string {
  const offset = 0x1F1E6 - 65;
  return [...iso.toUpperCase()].map(c => String.fromCodePoint(c.charCodeAt(0) + offset)).join("");
}

// Build sorted lookup (longest prefix first)
const SORTED = [...CODES].sort((a, b) => b.prefix.length - a.prefix.length);

export function getPhoneCountry(phone: string | null | undefined): CountryInfo | null {
  if (!phone) return null;
  // Normalise: if the number doesn't start with + try prepending one so we
  // can still detect "393299160781" as Italy just like "+393299160781"
  const raw = phone.trim();
  const normalized = raw.startsWith("+") ? raw : "+" + raw;
  for (const entry of SORTED) {
    if (normalized.startsWith(entry.prefix)) {
      return { flag: isoToFlag(entry.iso), name: entry.name, prefix: entry.prefix };
    }
  }
  return null;
}

// Sorted alphabetically for use in the country-code picker
export const PHONE_COUNTRIES: Array<{ prefix: string; flag: string; name: string }> =
  [...CODES]
    .filter((c, i, arr) => arr.findIndex(x => x.prefix === c.prefix) === i) // dedupe
    .map(c => ({ prefix: c.prefix, flag: isoToFlag(c.iso), name: c.name }))
    .sort((a, b) => a.name.localeCompare(b.name));
