// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://yaoaulvxrxgcitbfpapy.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlhb2F1bHZ4cnhnY2l0YmZwYXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzODEwOTEsImV4cCI6MjA5NDk1NzA5MX0.3ntNaAVizjMBwnaXxk7peNVWfhHkxXQSUenV037soXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});